image:
  repository: eu.gcr.io/gardener-project/gardener/extensions/os-suse-jeos
  tag: latest
  pullPolicy: IfNotPresent

resources: {}

osConfig:
  format: script # cloud-init
  bootCmd: "/bin/bash %s" # "/usr/bin/cloud-init clean && /usr/bin/cloud-init --file %s init"

controllers:
  concurrentSyncs: 5
  ignoreOperationAnnotation: false

disableControllers: []

